/* FX Studio — built-in presets.
 *
 * Each preset rebuilds one of the game's hardcoded effects out of FX Kit
 * primitives, using the constant values from laser/config.py (cited per
 * field), so you start from exactly what the game draws today.  Built-in
 * presets are read-only; "Save as preset" stores your own copies.
 * The engine's built-in characters keep their original effect code — these
 * presets only seed new FX.
 * `group` sorts the preset list; every effect carries its FX `tag` so other
 * characters' defend / deflect triggers can react to it.  The special-ability
 * presets (Fire, Lightning, Shadow, Holy, Ice & wind, Earth & poison, Arcane & cosmic, Energy) use keyframes (fx.keys).
 */
(function (G) {
"use strict";
G.FX_PRESETS = [
  {name: "Laser trail", group: "Trails", desc: "TrailComponent: TRAIL_LEN 50, W 1→5, flow 0.008, glow/dot 1",
   effects: [{prim: "ribbon", name: "Laser trail", tag: "trail", anchor: "figure", offset: [-8, 6],   // TRAIL_BACK / TRAIL_DOWN
     motion: {kind: "attached"}, color: {mode: "palette", flow_speed: 0.008},
     params: {max_points: 50, min_dist: 2, decay: 2, taper: true, w_tail: 1, w_head: 5, alpha: 220, head_glow_r: 1, head_dot_r: 1}}]},
  {name: "Blade trail", group: "Trails", desc: "The laser-trail ribbon pinned to the weapon tip",
   effects: [{prim: "ribbon", name: "Blade trail", tag: "trail", anchor: "wtip", motion: {kind: "attached"},
     color: {mode: "palette", flow_speed: 0.008},
     params: {max_points: 14, min_dist: 2, decay: 3, taper: true, w_tail: 1, w_head: 6, alpha: 220, head_glow_r: 4, head_dot_r: 2}}]},
  {name: "Crescent slash", group: "Slashes", desc: "CrescentWave: R 42, span 170, width 6.5, 5 ticks, 0.4 px/tick, centre 51 px behind the target",
   effects: [{prim: "arc", battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 0, knockback: 0},
     name: "Crescent slash", tag: "slash", anchor: "figure", offset: [0, 0], life_ticks: 5,
     motion: {kind: "travel", aim: "target", speed: 0.4}, color: {mode: "palette", flow_speed: 0.008},
     params: {radius: 42, span: 170, width: 6.5, tail: 0.95, segs: 16, grow: 0.85, core_alpha: 0.7, core_width: 0.3, orient: "motion", placement: "wrap_target", back: 51}}]},
  {name: "Through crescent", group: "Slashes", desc: "Through-slash: starts 26 px short, 10 px/tick, cuts through the target",
   effects: [{prim: "arc", battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 0, knockback: 0},
     name: "Through crescent", tag: "slash", anchor: "figure", life_ticks: 5,
     motion: {kind: "travel", aim: "target", speed: 10}, color: {mode: "palette", flow_speed: 0.008},
     params: {radius: 42, span: 170, width: 6.5, tail: 0.95, segs: 16, grow: 0.85, core_alpha: 0.7, core_width: 0.3, orient: "motion", placement: "through_target", lead: 26}}]},
  {name: "Cone bolt", group: "Shots", desc: "Projectile: PROJ_SPEED 8, radius 3, 220 ticks, 5-point trail",
   effects: [{prim: "sprite", battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 0},
     name: "Cone bolt", tag: "bolt", anchor: "haR", life_ticks: 220, emit: {count: 3, fan_deg: 90},   // SHOT_CONE_ANGLES ±45
     motion: {kind: "travel", aim: "target", speed: 8}, color: {mode: "palette", lut_index: 128},
     params: {shape: "bolt", radius: 3, stretch: 1, hot: false, halo: false, fade: true, trail_len: 5}}]},
  {name: "Zigzag bolt", group: "Shots", desc: "ZigzagProjectile: amplitude 55, frequency 0.18, hot streak",
   effects: [{prim: "sprite", battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 0},
     name: "Zigzag bolt", tag: "bolt", anchor: "haR", life_ticks: 220, emit: {count: 2},
     motion: {kind: "zigzag", aim: "target", speed: 8, amplitude: 55, freq: 0.18}, color: {mode: "palette", lut_index: 128},
     params: {shape: "bolt", radius: 3, stretch: 1, hot: true, fade: true, trail_len: 5}}]},
  {name: "Homing orb", group: "Shots", desc: "HomingProjectile: 0.5 × PROJ_SPEED with the pulsing halo",
   effects: [{prim: "sprite", battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 0},
     name: "Homing orb", tag: "orb", anchor: "haR", life_ticks: 220,
     motion: {kind: "homing", aim: "target", speed: 4, turn_deg: 6}, color: {mode: "palette", lut_index: 128},
     params: {shape: "orb", radius: 3, halo: true, fade: true, trail_len: 5}}]},
  {name: "Rich beam", group: "Beams", desc: "RichBeamProjectile: segmented, glowing, detaches and withers",
   effects: [{prim: "beam", battle: {deals_damage: true, damage: 8, pierce: true, rehit_ticks: 0, knockback: 0},
     name: "Rich beam", tag: "beam", anchor: "haR", life_ticks: 150, blend: "additive",
     motion: {kind: "travel", aim: "target", speed: 12}, color: {mode: "gradient", c1: "#ffffff", c2: "#3fb0ea"},
     params: {length: 260, w_start0: 10, w_start1: 4, w_end0: 4, w_end1: 1, segments: 14, glow: 8, pulse_hz: 6, jitter: 1.5, detach_ticks: 40}}]},
  {name: "Held beam", group: "Beams", desc: "A beam held from the hand, growing along the aim",
   effects: [{prim: "beam", battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 8, knockback: 0},
     name: "Held beam", tag: "beam", anchor: "haR", blend: "additive",
     motion: {kind: "attached", aim: "target"}, color: {mode: "gradient", c1: "#ffffff", c2: "#ff3a3a"},
     params: {length: 320, w_start0: 12, w_start1: 12, w_end0: 6, w_end1: 6, segments: 16, glow: 10, pulse_hz: 8, jitter: 1, grow_ticks: 8}}]},
  {name: "Petal orbs", group: "Orbs & auras", desc: "Petals: 3 orbs, hover 46 px, 70°/s, radius 8, #fbeef3. Lower Glow % / Glow size % for a crisper orb",
   effects: [{prim: "sprite", battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 0},
     name: "Petal orbs", tag: "petal", anchor: "figure", emit: {count: 3},
     motion: {kind: "orbit", orbit_rx: 46, orbit_ry: 46, orbit_deg: 1.12},   // 70 deg/s × 0.016 s
     color: {mode: "solid", c1: "#fbeef3"}, params: {shape: "orb", radius: 8, fade: false, trail_len: 0, glow: 100, glow_size: 100}}]},
  {name: "Energy sphere", group: "Orbs & auras", desc: "Radial glow + white core (the trail head, scaled up)",
   effects: [{prim: "glow", name: "Energy sphere", tag: "orb", anchor: "haR", motion: {kind: "attached"},
     color: {mode: "palette", lut_index: 128}, params: {r_start: 6, r_end: 18, a_center: 160, a_mid: 70, mid: 0.4, core_r: 5, fade: "none", pulse_hz: 4}}]},
  {name: "Afterimages", group: "Bursts & afterimages", desc: "Dash ghosts: every 2 ticks, 14-tick fade, alpha 150, crimson",
   effects: [{prim: "ghost", name: "Afterimages", tag: "ghost", anchor: "figure", motion: {kind: "attached"},
     color: {mode: "solid", c1: "#e12837"}, params: {interval: 2, ghost_life: 14, alpha: 150, max: 12}}]},
  {name: "Spark burst", group: "Bursts & afterimages", desc: "BurstParticle swarm: gravity, drag, shrinking sparks",
   effects: [{prim: "particles", name: "Spark burst", tag: "spark", anchor: "wtip", life_ticks: 1, motion: {kind: "static"},
     color: {mode: "gradient", c1: "#ffffff", c2: "#ff6a00"},
     params: {mode: "burst", count: 18, angle_deg: -30, spread_deg: 120, speed_min: 80, speed_max: 260, gravity: 420, drag: 0.94, size_min: 1.5, size_max: 4, size_over_life: "shrink", life_min_ms: 180, life_max_ms: 420}}]},
  {name: "Soft petal orbs", group: "Orbs & auras", desc: "Petal orbs with a dim, tight glow (Glow 35 %, size 60 %)",
   effects: [{prim: "sprite", battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 0},
     name: "Soft petal orbs", tag: "petal", anchor: "figure", emit: {count: 3},
     motion: {kind: "orbit", orbit_rx: 46, orbit_ry: 46, orbit_deg: 1.12},
     color: {mode: "solid", c1: "#fbeef3"}, params: {shape: "orb", radius: 6, fade: false, trail_len: 0, glow: 35, glow_size: 60}}]},

  // ---------------------------------------------------------------- special abilities
  // Built from the same primitives; keyframes (fx.keys) animate them.  Key
  // frames are action frames: a shot keeps playing its keys after the action ends.
  {name: "Fireball", group: "Fire", desc: "A blazing orb that accelerates (keyframed speed 3 → 9, ease in) with a rising ember trail",
   effects: [
     {prim: "sprite", name: "Fireball", tag: "fireball", anchor: "haR", life_ticks: 120,
      battle: {deals_damage: true, damage: 2, pierce: false, rehit_ticks: 0, knockback: 6},
      motion: {kind: "travel", aim: "target", speed: 3}, color: {mode: "solid", c1: "#ff7a1a"},
      params: {shape: "orb", radius: 5, fade: false, trail_len: 10, glow: 140, glow_size: 120},
      keys: [{frame: 6, ease: "in", set: {"motion.speed": 9}}]},
     {prim: "particles", name: "Ember trail", tag: "fireball", anchor: "haR", life_ticks: 120,
      motion: {kind: "travel", aim: "target", speed: 3}, color: {mode: "gradient", c1: "#ffd27a", c2: "#ff3300"},
      params: {mode: "stream", rate_per_s: 90, angle_deg: -90, spread_deg: 120, speed_min: 10, speed_max: 45, gravity: -80, drag: 0.95,
               size_min: 1.5, size_max: 3.5, size_over_life: "shrink", life_min_ms: 180, life_max_ms: 420},
      keys: [{frame: 6, ease: "in", set: {"motion.speed": 9}}]}]},
  {name: "Flame slash", group: "Fire", desc: "A fiery crescent that cuts through the target, swelling and thinning as it goes (keyframed radius / width, ease out)",
   effects: [
     {prim: "arc", name: "Flame slash", tag: "flame", anchor: "figure", life_ticks: 9,
      battle: {deals_damage: true, damage: 2, pierce: true, rehit_ticks: 0, knockback: 10},
      motion: {kind: "travel", aim: "target", speed: 9}, color: {mode: "gradient", c1: "#fff1a8", c2: "#ff4000"}, blend: "additive",
      params: {radius: 40, span: 170, width: 11, tail: 0.95, segs: 18, grow: 0.85, core_alpha: 0.8, core_width: 0.35, orient: "motion",
               placement: "through_target", lead: 26},
      keys: [{frame: 3, ease: "out", set: {"params.radius": 56, "params.width": 4, "color.c1": "#ffb35c"}}]},
     {prim: "particles", name: "Flame sparks", tag: "flame", anchor: "figure", life_ticks: 1, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#fff1a8", c2: "#ff4000"},
      params: {mode: "burst", count: 24, angle_deg: 0, spread_deg: 70, speed_min: 90, speed_max: 280, gravity: -40, drag: 0.93,
               size_min: 1.5, size_max: 4, size_over_life: "shrink", life_min_ms: 200, life_max_ms: 450}}]},
  {name: "Eruption", group: "Fire", desc: "Fire bursts up under the target: a swelling heat glow (keyframed, strong ease out) and a fountain of embers",
   effects: [
     {prim: "glow", name: "Eruption heat", tag: "flame", anchor: "target", life_ticks: 40, motion: {kind: "static"},
      battle: {deals_damage: true, damage: 2, pierce: true, rehit_ticks: 12, knockback: 8}, blend: "additive",
      color: {mode: "solid", c1: "#ff6a00"}, params: {r_start: 4, r_end: 4, a_center: 200, a_mid: 90, mid: 0.45, core_r: 3, fade: "out", pulse_hz: 6},
      keys: [{frame: 4, ease: "strong_out", set: {"params.r_start": 26, "params.r_end": 30, "params.core_r": 9}}]},
     {prim: "particles", name: "Eruption embers", tag: "flame", anchor: "target", life_ticks: 36, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#ffe08a", c2: "#ff2a00"},
      params: {mode: "stream", rate_per_s: 160, angle_deg: -90, spread_deg: 28, speed_min: 140, speed_max: 320, gravity: 380, drag: 0.97,
               size_min: 2, size_max: 4.5, size_over_life: "shrink", life_min_ms: 260, life_max_ms: 600}}]},

  {name: "Chain lightning", group: "Lightning", desc: "A crackling bolt that lashes out to full length (keyframed length, strong ease out) and flickers",
   effects: [{prim: "beam", name: "Chain lightning", tag: "lightning", anchor: "haR", life_ticks: 18, blend: "additive",
     battle: {deals_damage: true, damage: 2, pierce: true, rehit_ticks: 6, knockback: 4},
     motion: {kind: "attached", aim: "target"}, color: {mode: "gradient", c1: "#ffffff", c2: "#7fd4ff"},
     params: {length: 40, w_start0: 3, w_start1: 2.5, w_end0: 2, w_end1: 1, segments: 9, glow: 5, glow_color: "#3fa9ff", pulse_hz: 22, jitter: 4},
     keys: [{frame: 2, ease: "strong_out", set: {"params.length": 320}}, {frame: 5, ease: "linear", set: {"params.jitter": 8, "params.glow": 2}}]}]},
  {name: "Thunder strike", group: "Lightning", desc: "Lightning drops onto the target from above, with a flash and a spray of sparks",
   effects: [
     {prim: "beam", name: "Thunder bolt", tag: "lightning", anchor: "target", offset: [0, -260], life_ticks: 14, blend: "additive",
      battle: {deals_damage: true, damage: 3, pierce: true, rehit_ticks: 0, knockback: 12},
      motion: {kind: "static", aim: "angle", angle_deg: 90}, color: {mode: "gradient", c1: "#ffffff", c2: "#a8dcff"},
      params: {length: 270, w_start0: 5, w_start1: 2, w_end0: 3, w_end1: 1, segments: 8, glow: 7, glow_color: "#5ab8ff", pulse_hz: 30, jitter: 6}},
     {prim: "glow", name: "Strike flash", tag: "lightning", anchor: "target", life_ticks: 12, motion: {kind: "static"}, blend: "additive",
      color: {mode: "solid", c1: "#d8f0ff"}, params: {r_start: 6, r_end: 34, a_center: 230, a_mid: 90, mid: 0.4, core_r: 6, fade: "out", pulse_hz: 0}},
     {prim: "particles", name: "Strike sparks", tag: "lightning", anchor: "target", life_ticks: 1, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#ffffff", c2: "#5ab8ff"},
      params: {mode: "burst", count: 26, angle_deg: -90, spread_deg: 200, speed_min: 120, speed_max: 340, gravity: 600, drag: 0.94,
               size_min: 1, size_max: 3, size_over_life: "shrink", life_min_ms: 160, life_max_ms: 380}}]},
  {name: "Spark volley", group: "Lightning", desc: "Three crackling bolts that zigzag at the target, bright white-hot heads",
   effects: [{prim: "sprite", name: "Spark volley", tag: "lightning", anchor: "haR", life_ticks: 140, emit: {count: 3, fan_deg: 36},
     battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 0},
     motion: {kind: "zigzag", aim: "target", speed: 9, amplitude: 28, freq: 0.38}, color: {mode: "solid", c1: "#bfe8ff"}, blend: "additive",
     params: {shape: "bolt", radius: 2.5, stretch: 2.4, hot: true, fade: true, trail_len: 8, glow: 150, glow_size: 110}}]},

  {name: "Void orb", group: "Shadow", desc: "A slow homing orb of darkness that swells as it closes in (keyframed size / glow, strong ease in)",
   effects: [{prim: "sprite", name: "Void orb", tag: "void", anchor: "haR", life_ticks: 200,
     battle: {deals_damage: true, damage: 3, pierce: false, rehit_ticks: 0, knockback: 14},
     motion: {kind: "homing", aim: "target", speed: 3, turn_deg: 4}, color: {mode: "solid", c1: "#7a3cff"},
     params: {shape: "orb", radius: 4, halo: true, fade: false, trail_len: 12, glow: 160, glow_size: 130},
     keys: [{frame: 12, ease: "strong_in", set: {"params.radius": 11, "params.glow_size": 190, "color.c1": "#3b0a8f", "motion.speed": 4.5}}]}]},
  {name: "Shadow dash", group: "Shadow", desc: "Dark violet afterimages with a fading shadow trail behind the fighter",
   effects: [
     {prim: "ghost", name: "Shadow images", tag: "shadow", anchor: "figure", layer: "behind", motion: {kind: "attached"},
      color: {mode: "solid", c1: "#3a1466"}, params: {interval: 1, ghost_life: 18, alpha: 170, max: 16}},
     {prim: "ribbon", name: "Shadow trail", tag: "shadow", anchor: "figure", layer: "behind", motion: {kind: "attached"},
      color: {mode: "gradient", c1: "#120020", c2: "#8a4dff"},
      params: {max_points: 30, min_dist: 2, decay: 2, taper: true, w_tail: 1, w_head: 9, alpha: 200, head_glow_r: 3, head_dot_r: 1}}]},
  {name: "Void collapse", group: "Shadow", desc: "Orbs ring the target and spiral inward faster and faster (keyframed orbit radius / spin, strong ease in), then a dark flash",
   effects: [
     {prim: "sprite", name: "Collapsing orbs", tag: "void", anchor: "target", life_ticks: 40, emit: {count: 6},
      battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 10, knockback: 0},
      motion: {kind: "orbit", orbit_rx: 70, orbit_ry: 70, orbit_deg: 3}, color: {mode: "solid", c1: "#9b59ff"},
      params: {shape: "orb", radius: 3.5, fade: false, trail_len: 6, glow: 120, glow_size: 100},
      keys: [{frame: 10, ease: "strong_in", set: {"motion.orbit_rx": 6, "motion.orbit_ry": 6, "motion.orbit_deg": 14}}]},
     {prim: "glow", name: "Collapse flash", tag: "void", anchor: "target", start_frame: 9, life_ticks: 14, motion: {kind: "static"},
      battle: {deals_damage: true, damage: 2, pierce: true, rehit_ticks: 0, knockback: 16},
      color: {mode: "solid", c1: "#5a1fb8"}, params: {r_start: 4, r_end: 40, a_center: 220, a_mid: 100, mid: 0.5, core_r: 0, fade: "out", pulse_hz: 0}}]},

  {name: "Radiant beam", group: "Holy", desc: "A golden beam held from the hand that opens up and brightens (keyframed width / glow, ease out)",
   effects: [{prim: "beam", name: "Radiant beam", tag: "holy", anchor: "haR", blend: "additive",
     battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 6, knockback: 2},
     motion: {kind: "attached", aim: "target"}, color: {mode: "gradient", c1: "#ffffff", c2: "#ffd96a"},
     params: {length: 340, w_start0: 1, w_start1: 1, w_end0: 1, w_end1: 1, segments: 1, glow: 2, glow_color: "#ffe9a8", pulse_hz: 5, jitter: 0, grow_ticks: 8},
     keys: [{frame: 3, ease: "out", set: {"params.w_start0": 7, "params.w_start1": 7, "params.w_end0": 4, "params.w_end1": 4, "params.glow": 7}}]}]},
  {name: "Halo burst", group: "Holy", desc: "A ring of light orbs bursts outward around the fighter (keyframed orbit, elastic) with a golden flare",
   effects: [
     {prim: "sprite", name: "Halo ring", tag: "holy", anchor: "figure", life_ticks: 36, emit: {count: 8},
      battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 12, knockback: 10},
      motion: {kind: "orbit", orbit_rx: 12, orbit_ry: 12, orbit_deg: 4}, color: {mode: "solid", c1: "#ffe08a"},
      params: {shape: "orb", radius: 3, fade: true, trail_len: 4, glow: 90, glow_size: 90},
      keys: [{frame: 6, ease: "elastic", set: {"motion.orbit_rx": 80, "motion.orbit_ry": 80}}]},
     {prim: "glow", name: "Halo flare", tag: "holy", anchor: "figure", life_ticks: 18, motion: {kind: "attached"}, blend: "additive",
      color: {mode: "solid", c1: "#fff3b0"}, params: {r_start: 8, r_end: 64, a_center: 190, a_mid: 70, mid: 0.4, core_r: 8, fade: "out", pulse_hz: 0}},
     {prim: "particles", name: "Halo motes", tag: "holy", anchor: "figure", life_ticks: 1, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#ffffff", c2: "#ffc94a"},
      params: {mode: "burst", count: 36, angle_deg: 0, spread_deg: 360, speed_min: 90, speed_max: 240, gravity: -30, drag: 0.92,
               size_min: 1.5, size_max: 3, size_over_life: "shrink", life_min_ms: 300, life_max_ms: 650}}]},

  {name: "Ice shards", group: "Ice & wind", desc: "A tight volley of five frozen shards, crisp low glow",
   effects: [{prim: "sprite", name: "Ice shards", tag: "ice", anchor: "haR", life_ticks: 90, emit: {count: 5, fan_deg: 24},
     battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 3},
     motion: {kind: "travel", aim: "target", speed: 10}, color: {mode: "solid", c1: "#cfefff"},
     params: {shape: "bolt", radius: 2, stretch: 3, hot: false, fade: false, trail_len: 6, glow: 60, glow_size: 70}}]},
  {name: "Frost nova", group: "Ice & wind", desc: "Shards burst out in every direction from the fighter with an icy flash and frost motes",
   effects: [
     {prim: "sprite", name: "Nova shards", tag: "ice", anchor: "figure", life_ticks: 24, emit: {count: 10, fan_deg: 324},
      battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 0, knockback: 12},
      motion: {kind: "travel", aim: "facing", speed: 3}, color: {mode: "solid", c1: "#e6f8ff"},
      params: {shape: "bolt", radius: 2.2, stretch: 2.6, hot: true, fade: true, trail_len: 5, glow: 80, glow_size: 80},
      keys: [{frame: 3, ease: "strong_out", set: {"motion.speed": 9}}]},
     {prim: "glow", name: "Nova flash", tag: "ice", anchor: "figure", life_ticks: 16, motion: {kind: "attached"}, blend: "additive",
      color: {mode: "solid", c1: "#a8e6ff"}, params: {r_start: 6, r_end: 72, a_center: 170, a_mid: 60, mid: 0.4, core_r: 5, fade: "out", pulse_hz: 0}},
     {prim: "particles", name: "Frost motes", tag: "ice", anchor: "figure", life_ticks: 1, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#ffffff", c2: "#7fd0ff"},
      params: {mode: "burst", count: 30, angle_deg: 0, spread_deg: 360, speed_min: 60, speed_max: 200, gravity: 40, drag: 0.9,
               size_min: 1, size_max: 2.5, size_over_life: "shrink", life_min_ms: 300, life_max_ms: 700}}]},
  {name: "Wind blades", group: "Ice & wind", desc: "Two quick pale-green crescents that cut through the target one after the other",
   effects: [{prim: "arc", name: "Wind blades", tag: "wind", anchor: "figure", start_frame: 0, end_frame: 6, life_ticks: 6, emit: {every_ticks: 5},
     battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 0, knockback: 6}, blend: "additive",
     motion: {kind: "travel", aim: "target", speed: 11}, color: {mode: "gradient", c1: "#f2fff8", c2: "#4fd18b"},
     params: {radius: 34, span: 150, width: 4, tail: 0.9, segs: 16, grow: 0.8, core_alpha: 0.6, core_width: 0.3, orient: "motion",
              placement: "through_target", lead: 20}}]},
  {name: "Cyclone", group: "Ice & wind", desc: "A whirling column on the target: wind streaks spinning in a flat ring while gusts rise, tightening as it spins up",
   effects: [
     {prim: "sprite", name: "Cyclone streaks", tag: "wind", anchor: "target", life_ticks: 60, emit: {count: 8},
      battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 10, knockback: 0},
      motion: {kind: "orbit", orbit_rx: 44, orbit_ry: 12, orbit_deg: 9}, color: {mode: "solid", c1: "#d8fff0"},
      params: {shape: "orb", radius: 2, fade: false, trail_len: 9, glow: 50, glow_size: 80},
      keys: [{frame: 12, ease: "inout", set: {"motion.orbit_rx": 22, "motion.orbit_ry": 6, "motion.orbit_deg": 16}}]},
     {prim: "particles", name: "Cyclone gusts", tag: "wind", anchor: "target", life_ticks: 56, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#ffffff", c2: "#8fe8c0"},
      params: {mode: "stream", rate_per_s: 70, angle_deg: -90, spread_deg: 50, speed_min: 60, speed_max: 160, gravity: -60, drag: 0.96,
               size_min: 1, size_max: 2.5, size_over_life: "shrink", life_min_ms: 250, life_max_ms: 550}}]},

  {name: "Quake", group: "Earth & poison", desc: "The ground bursts under the target: heavy rock chunks fly up and fall back in a dust cloud",
   effects: [
     {prim: "particles", name: "Quake rocks", tag: "earth", anchor: "target", offset: [0, 10], life_ticks: 1, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#c8a070", c2: "#5a3a1e"},
      params: {mode: "burst", count: 28, angle_deg: -90, spread_deg: 130, speed_min: 150, speed_max: 380, gravity: 950, drag: 0.98,
               size_min: 2, size_max: 5, size_over_life: "constant", life_min_ms: 400, life_max_ms: 800}},
     {prim: "glow", name: "Quake dust", tag: "earth", anchor: "target", offset: [0, 10], life_ticks: 30, motion: {kind: "static"},
      battle: {deals_damage: true, damage: 3, pierce: true, rehit_ticks: 0, knockback: 18},
      color: {mode: "solid", c1: "#9a7a55"}, params: {r_start: 8, r_end: 46, a_center: 110, a_mid: 45, mid: 0.5, core_r: 0, fade: "out", pulse_hz: 0}}]},
  {name: "Toxic cloud", group: "Earth & poison", desc: "A lingering green cloud on the target that breathes in and out and bubbles, hurting while it lasts",
   effects: [
     {prim: "glow", name: "Toxic cloud", tag: "poison", anchor: "target", life_ticks: 120, motion: {kind: "static"},
      battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 20, knockback: 0},
      color: {mode: "solid", c1: "#7dff4a"}, params: {r_start: 6, r_end: 30, a_center: 120, a_mid: 55, mid: 0.55, core_r: 0, fade: "none", pulse_hz: 1.5},
      keys: [{frame: 6, ease: "out", set: {"params.r_start": 30, "params.r_end": 36}}]},
     {prim: "particles", name: "Toxic bubbles", tag: "poison", anchor: "target", life_ticks: 110, motion: {kind: "static"},
      color: {mode: "gradient", c1: "#d6ff9a", c2: "#3c8f1a"},
      params: {mode: "stream", rate_per_s: 22, angle_deg: -90, spread_deg: 80, speed_min: 10, speed_max: 40, gravity: -25, drag: 0.98,
               size_min: 1.5, size_max: 3.5, size_over_life: "grow", life_min_ms: 500, life_max_ms: 1000}}]},

  {name: "Arcane missiles", group: "Arcane & cosmic", desc: "Four magenta missiles fan out, then curve in and speed up toward the target",
   effects: [{prim: "sprite", name: "Arcane missiles", tag: "arcane", anchor: "haR", life_ticks: 160, emit: {count: 4, fan_deg: 120},
     battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 2},
     motion: {kind: "homing", aim: "target", speed: 4, turn_deg: 7}, color: {mode: "solid", c1: "#ff5ef2"}, blend: "additive",
     params: {shape: "orb", radius: 2.5, halo: false, fade: false, trail_len: 12, glow: 120, glow_size: 100},
     keys: [{frame: 8, ease: "in", set: {"motion.speed": 9}}]}]},
  {name: "Rune circle", group: "Arcane & cosmic", desc: "A flat ring of runes circles the fighter's feet over a soft blue aura (guards against contact)",
   effects: [
     {prim: "sprite", name: "Rune ring", tag: "arcane", anchor: "figure", offset: [0, 12], emit: {count: 6},
      battle: {deals_damage: true, damage: 1, pierce: true, rehit_ticks: 20, knockback: 6},
      motion: {kind: "orbit", orbit_rx: 34, orbit_ry: 10, orbit_deg: 2.5}, color: {mode: "solid", c1: "#8fd3ff"},
      params: {shape: "orb", radius: 2, fade: false, trail_len: 3, glow: 80, glow_size: 90}},
     {prim: "glow", name: "Rune aura", tag: "arcane", anchor: "figure", offset: [0, 4], motion: {kind: "attached"}, layer: "behind",
      color: {mode: "solid", c1: "#4aa8ff"}, params: {r_start: 22, r_end: 22, a_center: 60, a_mid: 25, mid: 0.5, core_r: 0, fade: "none", pulse_hz: 2}}]},
  {name: "Meteor", group: "Arcane & cosmic", desc: "A burning rock falls from the sky behind the fighter and slams into the target, speeding up as it drops",
   effects: [
     {prim: "sprite", name: "Meteor", tag: "meteor", anchor: "target", offset: [-150, -230], life_ticks: 90,
      battle: {deals_damage: true, damage: 4, pierce: false, rehit_ticks: 0, knockback: 22},
      motion: {kind: "travel", aim: "target", speed: 3}, color: {mode: "solid", c1: "#ff9a3c"},
      params: {shape: "orb", radius: 7, fade: false, trail_len: 14, glow: 150, glow_size: 110},
      keys: [{frame: 10, ease: "strong_in", set: {"motion.speed": 14}}]},
     {prim: "particles", name: "Meteor fire", tag: "meteor", anchor: "target", offset: [-150, -230], life_ticks: 90,
      motion: {kind: "travel", aim: "target", speed: 3}, color: {mode: "gradient", c1: "#ffe08a", c2: "#ff2a00"},
      params: {mode: "stream", rate_per_s: 120, angle_deg: -150, spread_deg: 60, speed_min: 20, speed_max: 70, gravity: -40, drag: 0.94,
               size_min: 2, size_max: 4.5, size_over_life: "shrink", life_min_ms: 200, life_max_ms: 450},
      keys: [{frame: 10, ease: "strong_in", set: {"motion.speed": 14}}]}]},
  {name: "Starfall", group: "Arcane & cosmic", desc: "Little stars rain down around the target in waves",
   effects: [{prim: "sprite", name: "Starfall", tag: "star", anchor: "target", offset: [0, -200], life_ticks: 40, emit: {every_ticks: 6, count: 3, fan_deg: 40},
     battle: {deals_damage: true, damage: 1, pierce: false, rehit_ticks: 0, knockback: 0}, blend: "additive",
     motion: {kind: "travel", aim: "angle", angle_deg: 90, speed: 7}, color: {mode: "solid", c1: "#fff6c8"},
     params: {shape: "bolt", radius: 1.8, stretch: 2.2, hot: true, fade: true, trail_len: 6, glow: 110, glow_size: 90}}]},

  {name: "Charged laser", group: "Energy", desc: "Energy gathers in the hand (keyframed charge, strong ease in), then a thin piercing laser fires",
   effects: [
     {prim: "glow", name: "Laser charge", tag: "laser", anchor: "haR", start_frame: 0, end_frame: 8, motion: {kind: "attached"}, blend: "additive",
      color: {mode: "solid", c1: "#ff4a6a"}, params: {r_start: 2, r_end: 2, a_center: 220, a_mid: 90, mid: 0.4, core_r: 1, fade: "none", pulse_hz: 10},
      keys: [{frame: 8, ease: "strong_in", set: {"params.r_start": 18, "params.r_end": 18, "params.core_r": 6}}]},
     {prim: "beam", name: "Charged laser", tag: "laser", anchor: "haR", start_frame: 8, life_ticks: 16, blend: "additive",
      battle: {deals_damage: true, damage: 3, pierce: true, rehit_ticks: 0, knockback: 10},
      motion: {kind: "attached", aim: "target"}, color: {mode: "gradient", c1: "#ffffff", c2: "#ff3a5a"},
      params: {length: 420, w_start0: 7, w_start1: 7, w_end0: 4, w_end1: 4, segments: 1, glow: 10, glow_color: "#ff6a80", pulse_hz: 14, jitter: 0, grow_ticks: 3},
      keys: [{frame: 12, ease: "linear", set: {"params.glow": 12}},
             {frame: 18, ease: "strong_in", set: {"params.w_start0": 1, "params.w_start1": 1, "params.w_end0": 0.5, "params.w_end1": 0.5, "params.glow": 1}}]}]}

];
})(window);
